---
name: Release
'on':
  push:
    tags:
      - '*'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy
        run: >-
          ansible-galaxy role import \
            --api-key ${{ secrets.GALAXY_API_KEY }} \
            --role-name prepare_dev_setup
            veerendra2 ansible-role-prepare_dev_setup
